### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by usovio** [ObsGynaeCam/CF2021#1]
I think it would be good to add the Audience snapshot link on the pages of both events (https://obsgynaecam.github.io/CF2021/handson1.html and https://obsgynaecam.github.io/CF2021/slide-and-quiz/) separately. Under “We would love to hear from you”, the current text (https://obsgynaecam.github.io/CF2021/#We_would_love_to_hear_from_you) says “Please give us some feedback for us to improve bettter next time”. This could be changed to: “Please give us some feedback through a short survey. This will help us to develop our event further.” Here you would put a hyperlink to “a short survey” which would take you to the Audience snapshot.

**Comment by sung** [comment]
You may have noticed that they ([here](https://github.com/ObsGynaeCam/CF2021/blob/main/slide-and-quiz/index.html) and [here](https://github.com/ObsGynaeCam/CF2021/blob/main/handson1.html)) both will land on (i.e. redirected) corresponding event pages, which I have already placed the feed back section in current release.

**Comment by usovio** [comment]
Sung, thanks for putting the quiz up to: https://obsgynaecam.github.io/CF2021/slide-and-quiz/mum.html#/quiz

At first, I could not find the "Take the quiz!" button and I had to scroll down a bit to see it. So, it would be better if the button was on top of the "Pregnancy lifestyle with common myths" title. It would also be good to shrink the font size of the "Quiz" on top of the page to allow more space for the box where the quiz is. Currently, I have to scroll down at every question to see the options.

At the end of the quiz there's this sentence:
"To find out more, read this article for a pregancy, this NHS website for an untrasound scan, and this BBC site for fetal reproduction and birth."
There was a typo (untrasound) - I suggest changing the wording to:
"To find out more, read this article about pregancy myths, this NHS website about ultrasound scan, and this BBC site for human reproduction and birth."

**Comment by sung** [comment]
Thanks. Some bits are beyond my controls (e.g. screen size),but hopefully
it's better.
